import { useCallback, useEffect, useMemo, useState } from "react";
import { LoaderCircle, Pencil, Plus, Save, Trash2, X } from "lucide-react";
import { useParams } from "react-router-dom";
import { adminFetch } from "../../services/adminApi";

type Item = Record<string, unknown> & { id: number };
type Field = { key: string; label: string; type?: "text" | "textarea" | "date" | "number" | "checkbox" | "tags"; required?: boolean };
type Config = { title: string; singular: string; endpoint: string; headline: string; fields: Field[]; readonly?: boolean };
const configs: Record<string, Config> = {
  skills: { title: "Compétences", singular: "compétence", endpoint: "skills", headline: "Technologies et niveaux de maîtrise.", fields: [{key:"name",label:"Nom",required:true},{key:"category",label:"Catégorie"},{key:"proficiency",label:"Niveau (%)",type:"number"},{key:"display_order",label:"Ordre",type:"number"},{key:"active",label:"Active",type:"checkbox"}] },
  experiences: { title: "Expériences", singular: "expérience", endpoint: "experiences", headline: "Votre parcours professionnel.", fields: [{key:"title",label:"Poste",required:true},{key:"company",label:"Entreprise",required:true},{key:"location",label:"Lieu"},{key:"start_date",label:"Début",type:"date",required:true},{key:"end_date",label:"Fin",type:"date"},{key:"description",label:"Description",type:"textarea"},{key:"technologies",label:"Technologies",type:"tags"},{key:"current",label:"Poste actuel",type:"checkbox"},{key:"active",label:"Visible",type:"checkbox"}] },
  educations: { title: "Formations", singular: "formation", endpoint: "educations", headline: "Diplômes et apprentissages.", fields: [{key:"diploma",label:"Diplôme",required:true},{key:"institution",label:"Établissement",required:true},{key:"location",label:"Lieu"},{key:"start_date",label:"Début",type:"date",required:true},{key:"end_date",label:"Fin",type:"date"},{key:"description",label:"Description",type:"textarea"},{key:"active",label:"Visible",type:"checkbox"}] },
  services: { title: "Services", singular: "service", endpoint: "services", headline: "Vos offres et domaines d’intervention.", fields: [{key:"title",label:"Titre",required:true},{key:"slug",label:"Slug",required:true},{key:"description",label:"Description",type:"textarea",required:true},{key:"icon",label:"Icône"},{key:"display_order",label:"Ordre",type:"number"},{key:"active",label:"Visible",type:"checkbox"}] },
  messages: { title: "Messages", singular: "message", endpoint: "contact-messages", headline: "Demandes reçues depuis le portfolio.", readonly: true, fields: [] },
};

export default function ContentPage() {
  const { resource = "skills" } = useParams(); const config = configs[resource] || configs.skills;
  const [items,setItems]=useState<Item[]>([]); const [editing,setEditing]=useState<Item|null>(null); const [open,setOpen]=useState(false); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState("");
  const load=useCallback(()=>{setLoading(true);adminFetch<Item[]>("/admin/"+config.endpoint).then(setItems).catch(e=>setError(e.message)).finally(()=>setLoading(false));},[config.endpoint]);
  useEffect(load,[load]);
  const columns=useMemo(()=>config.readonly?["name","email","subject","message","status"]:config.fields.filter(f=>!["description","technologies","active","current"].includes(f.key)).slice(0,4).map(f=>f.key),[config]);
  function start(item?:Item){setEditing(item||({id:0,active:true,display_order:0} as Item));setOpen(true)}
  async function remove(item:Item){if(!confirm("Confirmer la suppression ?"))return;await adminFetch("/admin/"+config.endpoint+"/"+item.id,{method:"DELETE"});load()}
  async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!editing)return;setSaving(true);setError("");const {id,...payload}=editing;try{await adminFetch("/admin/"+config.endpoint+(id?"/"+id:""),{method:id?"PUT":"POST",body:JSON.stringify(payload)});setOpen(false);load()}catch(err){setError(err instanceof Error?err.message:"Erreur")}finally{setSaving(false)}}
  return <section><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="font-semibold text-lime-300">Contenu</p><h1 className="mt-2 text-3xl font-bold">{config.title}</h1><p className="mt-2 text-slate-400">{config.headline}</p></div>{!config.readonly&&<button onClick={()=>start()} className="inline-flex items-center justify-center gap-2 rounded-xl bg-lime-300 px-5 py-3 font-bold text-slate-950"><Plus size={18}/> Ajouter</button>}</div>
    {error&&<div className="mt-6 rounded-xl border border-red-500/30 bg-red-500/10 p-4 text-red-300">{error}</div>}
    <div className="mt-8 overflow-hidden rounded-2xl border border-white/10 bg-slate-900">{loading?<div className="grid min-h-64 place-items-center"><LoaderCircle className="animate-spin text-lime-300"/></div>:items.length===0?<div className="p-12 text-center text-slate-400">Aucun élément pour le moment.</div>:<div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="bg-white/[.03] text-slate-400"><tr>{columns.map(c=><th key={c} className="px-5 py-4 capitalize">{c.replace("_"," ")}</th>)}<th className="px-5 py-4 text-right">Actions</th></tr></thead><tbody className="divide-y divide-white/5">{items.map(item=><tr key={item.id}>{columns.map(c=><td key={c} className="max-w-xs truncate px-5 py-4 text-slate-300">{String(item[c]??"—")}</td>)}<td className="px-5 py-4"><div className="flex justify-end gap-2">{!config.readonly&&<button onClick={()=>start(item)} className="rounded-lg border border-white/10 p-2"><Pencil size={16}/></button>}<button onClick={()=>void remove(item)} className="rounded-lg border border-red-500/20 p-2 text-red-400"><Trash2 size={16}/></button></div></td></tr>)}</tbody></table></div>}</div>
    {open&&editing&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4 backdrop-blur-sm"><form onSubmit={submit} className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-2xl border border-white/10 bg-slate-900 p-6"><div className="mb-6 flex items-center justify-between"><h2 className="text-xl font-bold">{editing.id?"Modifier":"Ajouter"} {config.singular}</h2><button type="button" onClick={()=>setOpen(false)}><X/></button></div><div className="grid gap-4 sm:grid-cols-2">{config.fields.map(field=><ResourceField key={field.key} field={field} value={editing[field.key]} onChange={value=>setEditing({...editing,[field.key]:value})}/>)}</div><button disabled={saving} className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl bg-lime-300 px-5 py-3 font-bold text-slate-950">{saving?<LoaderCircle className="animate-spin" size={18}/>:<Save size={18}/>} Enregistrer</button></form></div>}
  </section>;
}

function ResourceField({field,value,onChange}:{field:Field;value:unknown;onChange:(value:unknown)=>void}) {
  if(field.type==="checkbox")return <label className="flex items-center gap-3 self-end py-3 text-sm"><input type="checkbox" checked={Boolean(value)} onChange={e=>onChange(e.target.checked)} className="h-5 w-5"/>{field.label}</label>;
  const normalized=field.type==="tags"&&Array.isArray(value)?value.join(", "):String(value??"");
  return <label className={"admin-field "+(field.type==="textarea"?"sm:col-span-2":"")}><span>{field.label}</span>{field.type==="textarea"?<textarea rows={4} required={field.required} value={normalized} onChange={e=>onChange(e.target.value)}/>:<input type={field.type==="number"?"number":field.type==="date"?"date":"text"} required={field.required} value={normalized} onChange={e=>onChange(field.type==="number"?Number(e.target.value):field.type==="tags"?e.target.value.split(",").map(v=>v.trim()).filter(Boolean):e.target.value)}/>}</label>;
}
